version: "3.9"

services:

  ally_django:
    container_name: ally_django
    build:
      dockerfile: ./docker/django/Dockerfile
    image: ally_django
    volumes:
      - ./src:/root/src
    ports:
      - 80:8000
    env_file:
      - ./docker/django/.env
      - ./docker/rabbitmq/.env
    depends_on:
      - ally_mariadb
      - ally_redis
      - ally_rabbitmq
      - ally_celery

  ally_mariadb:
    container_name: ally_mariadb
    build:
      dockerfile: ./docker/mariadb/Dockerfile
    image: ally_mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - ./docker/mariadb/.env

  ally_phpmyadmin:
    container_name: ally_phpmyadmin
    build:
      dockerfile: ./docker/phpmyadmin/Dockerfile
    image: ally_phpmyadmin
    ports:
      - 8080:80
    env_file:
      - ./docker/phpmyadmin/.env
    depends_on:
      - ally_mariadb
  

  # Distributed Stock Scraping and Analysis (DSSA)

  ally_celery:
    container_name: ally_celery
    build:
      dockerfile: ./docker/celery/Dockerfile
    image: ally_celery
    volumes:
      - ./src:/root/src
    env_file:
      - ./docker/django/.env
      - ./docker/rabbitmq/.env
    depends_on:
      - ally_rabbitmq
      - ally_redis

  ally_rabbitmq:
    container_name: ally_rabbitmq
    build:
      dockerfile: ./docker/rabbitmq/Dockerfile
    image: ally_rabbitmq
    ports:
      - 5672:5672
    env_file:
      ./docker/rabbitmq/.env

  ally_redis:
    container_name: ally_redis
    build:
      dockerfile: ./docker/redis/Dockerfile
    image: ally_redis
    volumes:
      - ./data/redis:/var/lib/redis
    ports:
      - 6379:6379
