# Generated by Django 4.2.2 on 2023-07-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_remove_exercise_muscles_remove_muscle_exercises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='end',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='start',
        ),
        migrations.AddField(
            model_name='exerciseentry',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='day',
            field=models.DateField(auto_now=True),
        ),
    ]
