# Generated by Django 4.2.2 on 2023-07-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_remove_exerciselog_end_remove_exerciselog_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseentry',
            old_name='time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='exerciselog',
            old_name='last_modified',
            new_name='updated_at',
        ),
    ]
