# Generated by Django 4.2.2 on 2023-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_remove_exercise_main_muscles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
