# Generated by Django 4.2.2 on 2023-08-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_alter_exercisecollection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='rack_cup_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rack_safety_index',
            field=models.IntegerField(null=True),
        ),
    ]
