# Generated by Django 4.2.2 on 2023-08-04 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0011_exercise_rack_cup_index_exercise_rack_safety_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exercises', models.ManyToManyField(to='fitness.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSplitCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('splits', models.ManyToManyField(to='fitness.exercisesplit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
